# Dependencies
markdown:         kramdown
# highlighter:      pygments

gems:             [jekyll-paginate]

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            Christian Paulsen
tagline:          'A blog'
description:      'A blog'
url:              http://christianpaulsen.com
baseurl:          /

author:
  name:           'Christian Paulsen'
  url:            https://twitter.com/ebertx

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ebertx/ebertx.github.io
